apiVersion: v1
kind: ServiceAccount
metadata:
  name: metric-grafana
  namespace: metric
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metric-grafana
rules:
  - apiGroups: [""]
    resources:
      - componentstatuses
      - endpoints
      - namespaces
      - nodes
      - pods
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metric-grafana
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metric-grafana
subjects:
- kind: ServiceAccount
  name: metric-grafana
  namespace: metric
